services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: iptracker-rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:17.4
    container_name: iptracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: iptracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/tmp/pg_hba.conf
      - ./postgres-config/copy_hba.sh:/docker-entrypoint-initdb.d/50-copy-hba.sh
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c wal_keep_size=64MB
      -c archive_mode=on
      -c archive_command='cd .'

  iptracker-db-replica:
    image: postgres:17.4
    container_name: iptracker-db-replica
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    depends_on:
      - postgres
    ports:
      - "5433:5432"
    entrypoint: ["/bin/bash", "-c", "
      until pg_isready -h postgres -U app; do echo 'Waiting for primary...'; sleep 1; done && \
      rm -rf /var/lib/postgresql/data/* && \
      pg_basebackup -h postgres -D /var/lib/postgresql/data -U app -Fp -Xs -P -R && \
      chown -R postgres:postgres /var/lib/postgresql/data && \
      chmod 0700 /var/lib/postgresql/data && \
      exec su - postgres -c '/usr/lib/postgresql/17/bin/postgres -D /var/lib/postgresql/data'
    "]
    volumes:
      - pgdata-replica:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.8
    container_name: iptracker-flyway
    depends_on:
      - postgres
    volumes:
      - ./IpConnectTracker.WriterService.DataAccess.PostgreSQL/Migrations:/flyway/sql
    command: >
      -url=jdbc:postgresql://postgres:5432/iptracker
      -user=app
      -password=secret
      migrate

  writer-service:
    build:
      context: .
      dockerfile: ./IpConnectTracker.WriterService/Dockerfile
    container_name: iptracker-writer
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      Rabbit__Host: iptracker-rabbit
      Rabbit__Port: 5672
      Rabbit__QueueName: ip_connects
      Rabbit__UserName: guest
      Rabbit__Password: guest
      Postgres__ConnectionString: Host=iptracker-db;Port=5432;Database=iptracker;Username=app;Password=secret

  reader-service:
    build:
      context: .
      dockerfile: ./IpConnectTracker.ReaderService.Api/Dockerfile
    container_name: iptracker-reader
    ports:
      - "5109:8080"
    depends_on:
      - iptracker-db-replica
    environment:
      Postgres__ConnectionString: Host=iptracker-db-replica;Port=5432;Database=iptracker;Username=app;Password=secret

volumes:
  pgdata:
  pgdata-replica:
